### ISSUE TITLE
Disable /send while in certain servers

### ISSUE THREAD

**Issue by JustLeader69420** [OskarsMC-Plugins/send#1]
Hey, could it be done that the plugin would create a config file in which you could edit messages and on which servers /send can be executed on? Thanks

**Comment by OskarZyg** [comment]
I Will work on it.

**Comment by JustLeader69420** [comment]
Great to hear that, tell me when it's done and I will love to use this! :D

**Comment by OskarZyg** [comment]
Just a small question: what exactly are you trying to use this for? I can't really find a proper use case for this feature.

**Comment by JustLeader69420** [comment]
So, when admins have perms for everything on the bungeecord, I don't want for someone to join as them and just send themselves away from the auth server

**Comment by OskarZyg** [comment]
I have implemented this in build https://github.com/OskarsMC-Plugins/send/actions/runs/843350433, if you have any issues with the feature please open a new issue.
