### ISSUE TITLE
Send player from specific server [improvement]

### ISSUE THREAD

**Issue by MastoryMd5** [OskarsMC-Plugins/send#2]
It would be coool if you could use a command like 
`/send Hub-1 Hub-2` 
in order to teleport players from Hub-1 server to Hub-2 server

Thanks for your time!

**Comment by OskarZyg** [comment]
This sounds like a great feature to add, however, I am not entirely sure how the plugin should act if there is a player with the same name as a server. Maybe I should add a prefix? (eg: `s:server`, `p:playername`)

**Comment by MastoryMd5** [comment]
Well for the server can be used @ or # in front of the server name and then for the players just the name

**Comment by OskarZyg** [comment]
I have implemented this in build https://github.com/OskarsMC-Plugins/send/actions/runs/843350433, if you have any issues with the feature please open a new issue.
