### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by tommasobenatti** [OskarsMC-Plugins/send#3]
Hi, I use LuckPermsVelocity for the perms handling, I've set the permission `osmc.send.send` but when I do 
`/send player _Tbenatti_ Kingdoms` it keeps saying `You do not have permission to do that` but I have the permission setted up

**Comment by SladeHazard** [comment]
You need to open it's config and change     server-blacklist=false
to true so:
    server-blacklist=true

**Comment by tommasobenatti** [comment]
Ok, is there any reload command or I need to restart?

**Comment by SladeHazard** [comment]
restart dumbass

**Comment by tommasobenatti** [comment]
bruh

**Comment by SladeHazard** [comment]
dont forget to close the ticket

**Comment by OskarZyg** [comment]
I'm assuming that fixed it?
