### ISSUE TITLE
Permission Check Assumes Blacklist is enabled and will not function without it being enabled

### ISSUE THREAD

**Issue by SladeHazard** [OskarsMC-Plugins/send#4]
https://github.com/OskarsMC-Plugins/send/blob/ce01cd2983e4f9ee151d024017cd276410de160b/src/main/java/com/oskarsmc/send/command/SendCommand.java#L199

Noobfire — Today at 6:54 AM
say heres mistake of not returning true if blacklist is disabled
for author

**Comment by OskarZyg** [comment]
What?

**Comment by OskarZyg** [comment]
Nevermind- Will fix
